# Chrome capabilities example for Appium
appium:deviceName: "Pixel 9a"
platformName: "Android"
appium:platformVersion: "16.0"
appium:udid: "emulator-5554"
browserName: "Chrome"
appium:automationName: "UiAutomator2"
appium:autoDownloadEnabled: true
appium:chromedriverAutoDownload: true
appium:noReset: true
appium:adbExecTimeout: 60000
